{% set name = "teip" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/greymd/teip/archive/v{{ version }}.tar.gz
  sha256: c9e45d9f5fb263a67c42907d05d8a20dd62b910175270a59decc475e66ea6031

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - libclang
    - oniguruma

test:
  commands:
    - teip --help

about:
  home: https://github.com/greymd/teip
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Masking tape to help commands do one thing well
  dev_url: https://github.com/greymd/teip

extra:
  recipe-maintainers:
    - danielnachun
