context:
  version: "2.3.3"

package:
  name: teip
  version: ${{ version }}

source:
  url: https://github.com/greymd/teip/archive/v${{ version }}.tar.gz
  sha256: cc735acf21f248dfabbc368835f044b99db8e1bc7fb89678681e5c68b7fee236

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - libclang
  host:
    - oniguruma

tests:
  - script:
      - teip --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Masking tape to help commands do one thing well
  homepage: https://github.com/greymd/teip
  repository: https://github.com/greymd/teip

extra:
  recipe-maintainers:
    - danielnachun
