context:
  version: 2.3.2

package:
  name: teip
  version: ${{ version }}

source:
  url: https://github.com/greymd/teip/archive/v${{ version }}.tar.gz
  sha256: c9e45d9f5fb263a67c42907d05d8a20dd62b910175270a59decc475e66ea6031

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - libclang
    - oniguruma

tests:
  - script:
      - teip --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Masking tape to help commands do one thing well
  homepage: https://github.com/greymd/teip
  repository: https://github.com/greymd/teip

extra:
  recipe-maintainers:
    - danielnachun
